### ISSUE TITLE
Feature Request : Allow spaces in category

### ISSUE THREAD

**Issue by jonthn** [jsimonet/IRC-Client-Plugin-UserPoints#2]
When using this plugin you may want to write something like

`user++ perl coder`

currently I use :

`user++ perl_coder`

And my proposition doesn't necessarily mean to add 1 point in 'perl' and 1 point in 'coder' maybe should support something like :

`user++ "perl coder"`

But it's up to you to choose what's doable with the current code.

**Comment by julienbu** [comment]
\o/ \o/ \o/ \o/ \o/  Youhou !!!!! \o/ \o/ \o/ \o/ \o/
